# Concatenating DataFrames

- Concatenating DataFrames means combining them either by stacking them on top of each other (vertically) or placing them side by side (horizontally). In order to Concatenate dataframe, we use different methods which are as follows:

In [19]:
import pandas as pd

data1 = {
    'Name':['Aditya','Sahil','Tejas'],
    'Age':[20,18,23]
}
data2 = {
    'Name':['Pranav',"Nilesh",'Tejas'],
    'Age':[19,20,23]
}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

1. Concatenating DataFrame using .concat()

In [10]:
read =pd.concat([df1,df2]) 
read

     Name  Age
0  Aditya   20
1   Sahil   18
2   Tejas   23
0  Pranav   19
1  Nilesh   20
2   Tejas   23

In [11]:
pd.concat([df1,df2], ignore_index=True) # We get correct indexing

     Name  Age
0  Aditya   20
1   Sahil   18
2   Tejas   23
3  Pranav   19
4  Nilesh   20
5   Tejas   23

2. Add data horizontally

In [34]:
read =pd.concat([df1,df2], axis = 1, ignore_index=True)
read

        0   1       2   3
0  Aditya  20  Pranav  19
1   Sahil  18  Nilesh  20
2   Tejas  23   Tejas  23

3. Add Data vertically

In [35]:
read =pd.concat([df1,df2], axis = 0, ignore_index=True)
read

     Name  Age
0  Aditya   20
1   Sahil   18
2   Tejas   23
3  Pranav   19
4  Nilesh   20
5   Tejas   23